// Supabase Config
const SUPABASE_URL = 'https://jccjcxwyxhvxaebgumim.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjY2pjeHd5eGh2eGFlYmd1bWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxNjQzMzYsImV4cCI6MjA5MDc0MDMzNn0.WFkYY72zI9bwV4d3H5xx8zsmK-inZN5lmxvEjfHbp9M';
